#!/usr/bin/env bash
# scripts/bootstrap.sh — VibeShop 一键启动（首次 clone / 首次开发都能直接跑）。
#
# 逻辑：
#   1. 检测必备工具（go / docker / openssl / curl）
#   2. 缺 deploy/docker/.env  → 用 openssl 生成开发用随机密码并写入
#   3. 缺 configs/dev.yaml    → 从 .env 渲染 DSN 并写入
#   4. make infra-up 起中间件（含 healthy 等待）
#   5. make migrate 跑 schema 迁移（goose up all）
#   6. 前台启动应用（Ctrl+C 退出）
#
# 幂等：再跑一次只会跳过已存在的 .env / dev.yaml，重新拉中间件 + 跑迁移 + 启动。
# 不破坏：永远不会覆盖已存在的 .env / dev.yaml；首次生成后请妥善保管。
#
# 退出码：0=正常 Ctrl+C；非 0=任一步失败。

set -euo pipefail

# ===== 颜色与日志 =====

if [[ -t 1 ]]; then
  C_R=$'\033[0;31m'; C_G=$'\033[0;32m'; C_Y=$'\033[0;33m'; C_B=$'\033[0;34m'; C_N=$'\033[0m'
else
  C_R=""; C_G=""; C_Y=""; C_B=""; C_N=""
fi

step() { echo "${C_B}==>${C_N} $*"; }
ok()   { echo "${C_G}✓${C_N} $*"; }
warn() { echo "${C_Y}⚠${C_N} $*"; }
err()  { echo "${C_R}✗${C_N} $*" >&2; }

# ===== 路径 =====

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ROOT_DIR=$(cd -- "$SCRIPT_DIR/.." &>/dev/null && pwd)
ENV_FILE="$ROOT_DIR/deploy/docker/.env"
DEV_YAML="$ROOT_DIR/configs/dev.yaml"

cd "$ROOT_DIR"

# ===== Step 1: 检测工具 =====

step "检测必备工具"
missing=()
for cmd in go docker openssl curl make; do
  if ! command -v "$cmd" &>/dev/null; then
    missing+=("$cmd")
  fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
  err "缺少工具：${missing[*]}"
  echo "  请先安装它们再重试。Linux/WSL2 通常: apt install golang docker.io openssl curl make"
  exit 1
fi
if ! docker info &>/dev/null; then
  err "docker daemon 不可用（docker info 失败）"
  echo "  Linux: sudo systemctl start docker"
  echo "  WSL2: 启动 Docker Desktop / 或在 WSL 内 sudo service docker start"
  exit 1
fi
ok "go / docker / openssl / curl / make 都在"

# ===== Step 2: 生成或确认 .env =====

if [[ ! -f "$ENV_FILE" ]]; then
  step "首次运行：生成 deploy/docker/.env（开发用随机密码）"
  warn "这是开发用密码，仅本地有效；.env 已在 .gitignore，不会 commit"

  MYSQL_ROOT_PWD=$(openssl rand -base64 24 | tr -d '=+/' | head -c 32)
  MYSQL_PWD=$(openssl rand -base64 24 | tr -d '=+/' | head -c 32)
  # PG 密码必须 URL-safe（pgx 按 URL 解析 DSN）
  PG_PWD=$(openssl rand -hex 24)
  REDIS_PWD=$(openssl rand -base64 24 | tr -d '=+/' | head -c 32)
  JWT_SECRET=$(openssl rand -base64 48 | tr -d '=' | head -c 64)

  # 端口选择：默认用标准端口；BOOTSTRAP_PORTS_SHIFT=1 时全部错开 +1，
  # 用于解决"WSL2 / 本机 / Windows 服务" 占用 3306 等标准端口的情况。
  if [[ "${BOOTSTRAP_PORTS_SHIFT:-0}" == "1" ]]; then
    HOST_MYSQL=3307; HOST_PG=5433; HOST_REDIS=6380; HOST_NATS=4223; HOST_NATS_MON=8223
    PORT_HINT=$'\n# 端口已错开（BOOTSTRAP_PORTS_SHIFT=1）'
  else
    HOST_MYSQL=3306; HOST_PG=5432; HOST_REDIS=6379; HOST_NATS=4222; HOST_NATS_MON=8222
    PORT_HINT=""
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# 开发用随机密码，本地有效。生产部署请重新生成。
# 详见 docs/dev-workflow.md 环境变量参考表。

# ====== MySQL ======
VIBESHOP_MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PWD
VIBESHOP_MYSQL_USER=vibeshop
VIBESHOP_MYSQL_PASSWORD=$MYSQL_PWD

# ====== PostgreSQL ======
VIBESHOP_PG_USER=vibeshop
VIBESHOP_PG_PASSWORD=$PG_PWD

# ====== Redis ======
VIBESHOP_REDIS_PASSWORD=$REDIS_PWD

# ====== JWT ======
VIBESHOP_JWT_SECRET=$JWT_SECRET
$PORT_HINT
VIBESHOP_MYSQL_HOST_PORT=$HOST_MYSQL
VIBESHOP_PG_HOST_PORT=$HOST_PG
VIBESHOP_REDIS_HOST_PORT=$HOST_REDIS
VIBESHOP_NATS_HOST_PORT=$HOST_NATS
VIBESHOP_NATS_MON_HOST_PORT=$HOST_NATS_MON
EOF
  chmod 600 "$ENV_FILE"
  ok "$ENV_FILE 已生成（chmod 600）"
else
  ok "deploy/docker/.env 已存在，跳过"
fi

# ===== Step 3: 加载 .env，生成或确认 dev.yaml =====

# 从已存在的 .env 加载（包括首次刚生成的）
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

# 默认主机端口（与 docker-compose.infra.yml 默认值一致）
MYSQL_PORT="${VIBESHOP_MYSQL_HOST_PORT:-3306}"
PG_PORT="${VIBESHOP_PG_HOST_PORT:-5432}"
REDIS_PORT="${VIBESHOP_REDIS_HOST_PORT:-6379}"
NATS_PORT="${VIBESHOP_NATS_HOST_PORT:-4222}"

if [[ ! -f "$DEV_YAML" ]]; then
  step "首次运行：生成 configs/dev.yaml（DSN 从 .env 渲染）"

  cat > "$DEV_YAML" <<EOF
# Generated by scripts/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# 开发配置；密钥从 deploy/docker/.env 渲染。已在 .gitignore，不会 commit。
# 详见 docs/dev-workflow.md。

app:
  name: "vibeshop"
  env: "dev"
  debug: true

gateway:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "30s"

database:
  mysql:
    dsn: "${VIBESHOP_MYSQL_USER}:${VIBESHOP_MYSQL_PASSWORD}@tcp(127.0.0.1:${MYSQL_PORT})/vibeshop?charset=utf8mb4&parseTime=True&loc=Local"
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: "1h"
  postgres:
    dsn: "postgres://${VIBESHOP_PG_USER}:${VIBESHOP_PG_PASSWORD}@127.0.0.1:${PG_PORT}/vibeshop_content?sslmode=disable"
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: "1h"

redis:
  addr: "127.0.0.1:${REDIS_PORT}"
  password: "${VIBESHOP_REDIS_PASSWORD}"
  pool_size: 100
  min_idle_conns: 10

messaging:
  nats:
    url: "nats://127.0.0.1:${NATS_PORT}"
    jetstream: true

oss:
  provider: "local"
  local_path: "./uploads"

auth:
  jwt_secret: "${VIBESHOP_JWT_SECRET}"
  access_token_ttl: "2h"
  refresh_token_ttl: "168h"

ai:
  default_model: "ollama-qwen2"
  ollama_url: "http://localhost:11434"
  daily_token_budget: 100000

observability:
  log_level: "debug"
  log_format: "console"
  tracing:
    enabled: true
    exporter: "jaeger"
    endpoint: "localhost:4317"
  metrics:
    enabled: true
    port: 9100
EOF
  chmod 600 "$DEV_YAML"
  ok "$DEV_YAML 已生成（chmod 600）"
else
  ok "configs/dev.yaml 已存在，跳过"
fi

# ===== Step 4: 中间件 =====

step "启动中间件（make infra-up）"
if ! make -s infra-up; then
  err "infra-up 失败。常见原因 + 修复："
  echo
  echo "  ${C_Y}[端口冲突]${C_N} 本机 / Windows / WSL2 已经占用 3306/5432/6379 等"
  echo "    → 删除已生成配置后用错位端口重跑："
  echo "        rm deploy/docker/.env configs/dev.yaml"
  echo "        BOOTSTRAP_PORTS_SHIFT=1 ./scripts/bootstrap.sh"
  echo "      （MySQL→3307, PG→5433, Redis→6380, NATS→4223）"
  echo
  echo "  ${C_Y}[Docker daemon]${C_N} 未启动"
  echo "    → Linux: sudo systemctl start docker"
  echo "    → WSL2:  启动 Docker Desktop"
  echo
  echo "  ${C_Y}[密码含特殊字符]${C_N} 手改 .env 时引入 \$ % 等"
  echo "    → openssl 生成的不会，但手改时务必避免（详见 .env.example 注释）"
  exit 1
fi
ok "中间件 healthy"

# ===== Step 5: 迁移 =====

step "应用 schema 迁移（make migrate）"
if ! make -s migrate; then
  err "migrate 失败。可用 make migrate-status 看详情；scripts/migration/{mysql,pg}/ 是 SQL 来源"
  exit 1
fi
ok "迁移完成"

# ===== Step 6: 前台启动应用 =====

step "启动应用（前台运行，Ctrl+C 退出）"
echo "  健康检查: curl http://localhost:${VIBESHOP_APP_HOST_PORT:-8080}/health"
echo "  API 入口: POST /api/v1/auth/{register,login,refresh,logout}"
echo
exec make run
